---
    - vars_prompt:
      name: vhost_option
      prompt: "Do you want to enable nginx virtual host. Choose from these options(php,node,none)"  
      default: "none"
      private: no     
    - name: Install nginx
      apt: 
       name: nginx 
       state: latest

    - name: Setup php VirtualHost
      template:
       src: "roles/nginx/templates/nginxphp.j2"
       dest: "/etc/nginx/sites-available/{{ http_conf }}"
       when: vhost_option == "php"
    - name: install fastcgi (for php-fpm nginx)
      apt: 
       name: php-fpm
       state: latest
       update_cache: yes
      when: vhost_option == "php"     

    - name: Setup node Virtualhost  
      template:
       src: "roles/nginx/templates/nginxnode.j2"
       dest: "/etc/nginx/sites-available/{{ http_conf }}"
       when: vhost_option == "node"


    - name: create symlink
      file:
        src: /etc/nginx/sites-available/{{ http_conf }}
        dest: /etc/nginx/sites-enabled/{{ http_conf }}
        state: link
        notify: restart nginx