- name: start the Server Playbook
  hosts: all
  become: yes
  vars_files:
     - vars/default.yml
  vars_prompt:
    - name: framework_option
      prompt: "Which framework do you want to install (php/node/none)"  
      default: "none"
      private: no   
    - name: database_option
      prompt: "Which database system you want to install (mysql/mongodb/none)"
      default: "none"
      private: no 
    - name: webserver_option
      prompt: "Which web server system you want to install (apache/nginx/none)"
      default: "apache" 
      private: no
    - name: redis_option
      prompt: "Do you want to install redis (y/n)"  
      default: "n"
      private: no   
    - name: supervisor_option
      prompt: "Do you want to install supervisor (y/n)"
      default: "n"
      private: no
    - name: elasticsearch_option
      prompt: "Do you want to install Elasticsearch (y/n)"
      default: "n"
      private: no  
    - name: awstools_option
      prompt: "Do you want to install AWS EC2 related tools(eg. mon-tools,agents etc.)" 
      default: "n"
      private: no 
  roles: 
     - system
     - { role: apache, when: webserver_option == "apache" }
     - { role: nginx, when: webserver_option == "nginx" }
     - { role: php, when: framework_option == "php"}
     - { role: node, when: framework_option == "node"}
     - { role: mysql, when: database_option == "mysql" }
     - { role: mongodb, when: database_option == "mongodb" }
     - { role: redis, when: redis_option == "y"}
     - { role: supervisor, when: supervisor_option == "y"}
     - { role: elasticsearch, when: elasticsearch_option == "y"}
     - { role: awstools, when: awstools_option == "y" }
     - ssl
     - firewall
  handlers:
     - name: restart apache2
       service: name=apache2 state=restarted 
     - name: restart nginx
       service: name=nginx state=restarted  
     - name: restart mongodb
       service: name=mongod state=restarted
     - name: restart mysql
       service: name=mysql state=restarted
     - name: restart fail2ban
       service: name=fail2ban state=restarted
               

  