---
        - name: Enable ufw 
          ufw:
            state: enabled
            logging: 'on'
        - name: Allow OpenSSH on ufw
          ufw:
            rule: allow
            name: OpenSSH
        - name: Allow port 80 on ufw
          ufw:
            rule: allow
            port: '80' 
        - name: Allow port 443 on ufw
          ufw:
            rule: allow
            port: '443'  
        - name: Reload ufw
          ufw:
            state: reloaded
