---
        -  name: Add certbot repository
           apt_repository:
            repo: 'ppa:certbot/certbot'
        -  name: Install certbot
           apt:
            name: "{{ item }}"
            update_cache: yes
            state: present
           with_items: 
             - certbot
             - python-certbot-apache