--- 
        -  name: Add PHP PPA repository
           apt_repository:
            repo: 'ppa:ondrej/php'
        - name: Install PHP packages through APT
          apt: 
            name: "{{ item }}"
            update_cache: yes 
            force_apt_get: yes
            state: present
          with_items:
              - 'php7.2'
              - 'php7.2-xml'
              - 'php7.2-cli'
              - 'php7.2-mbstring'
              - 'php7.2-bcmath'
              - 'php7.2-common'
              - 'php7.2-zip'
              - 'php7.2-curl'
              - 'php7.2-gmp'
              - 'php7.2-mysql'
              - 'php7.2-gd'
              - 'php7.2-opcache'
              - 'php7.2-json'
              - 'php-redis'
        - name: install composer
          shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          args:
            creates: /usr/local/bin/composer       